Update Config to support ConfigParser keyword arguments
AnswerDotAI/fastcore pull request #659
Opened 2024-12-22 19:25 UTC by ncoop57

This PR adds a `cfg_kwargs` argument to the Config object in the foundations module. This allows a user to pass keyword arguments directly to the ConfigParser object, allowing for things like overriding the behavior on how inline comments are handled. An example showcasing this functionality is also added to the docs.

2024-12-22 19:36 UTC, ncoop57 commented
The integration test failure looks to be unrelated

2024-12-22 19:43 UTC, jph00 commented
Yeah the integration test issue is due to a new bug in scipy, which has been fixed upstream but not released yet.

2024-12-22 19:44 UTC, jph00 requested changes
Thank you! Just a minor issue below.

2024-12-22 19:44 UTC, jph00 commented on nbs/02_foundation.ipynb
Could you install ipywidgets (IIRC) and re-run the cell with `/Users/nathan/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html` so that warning doesn't turn up in the docs?

2024-12-23 15:14 UTC, ncoop57 commented on nbs/02_foundation.ipynb
Okay, this is fixed now, good catch!

2024-12-26 15:03 UTC, ncoop57 commented on nbs/02_foundation.ipynb
@jph00 anything else needed to get this merged in?

2024-12-26 19:56 UTC, jph00 commented on nbs/02_foundation.ipynb
Oops sorry got a bit behind over the xmas period! :O

2024-12-26 19:56 UTC, merged